name: Checks

on:
  - pull_request

env:
  node_version: 18

jobs:
  # Use a Common Setup workflow
  call_setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: call_setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
